"""initial_schema

Revision ID: 599b567a41fc
Revises: 
Create Date: 2026-09-25 23:33:41.191547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599b567a41fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('domains', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campus')),
    sa.UniqueConstraint('name', name=op.f('uq_campus_name'))
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('icon', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_category_slug'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('whatsapp', sa.String(length=16), nullable=False),
    sa.Column('show_phone', sa.Boolean(), nullable=False),
    sa.Column('show_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('profile_visible', sa.Boolean(), nullable=False),
    sa.Column('contact_visible', sa.Boolean(), nullable=False),
    sa.Column('search_history', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=64), nullable=True),
    sa.Column('cover', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_user_campus_id_campus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_campus_id'), ['campus_id'], unique=False)

    op.create_table('account_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_account_token_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_account_token_token_hash'))
    )
    op.create_table('admin_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name=op.f('fk_admin_action_admin_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_action'))
    )
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_login_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_history'))
    )
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_history_user_id'), ['user_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_unread', ['user_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('negotiable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('sale_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("condition IN ('new','like_new','good','fair')", name=op.f('ck_product_valid_condition')),
    sa.CheckConstraint("status IN ('draft','available','reserved','sold','hidden','removed')", name=op.f('ck_product_valid_status')),
    sa.CheckConstraint('price >= 0 AND price <= 99999999.99', name=op.f('ck_product_valid_price')),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], name=op.f('fk_product_buyer_id_user')),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_product_campus_id_campus')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_product_category_id_category')),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name=op.f('fk_product_seller_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_city'), ['city'], unique=False)
        batch_op.create_index('ix_product_discover', ['campus_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_seller_id'), ['seller_id'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], name=op.f('fk_report_reporter_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report'))
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_status'), ['status'], unique=False)

    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=140), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_search_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history'))
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_history_user_id'), ['user_id'], unique=False)

    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_session_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_session_token_hash'))
    )
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_session_user_id'), ['user_id'], unique=False)

    op.create_table('analytics_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_analytics_event_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_event'))
    )
    with op.batch_alter_table('analytics_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_event_product_id'), ['product_id'], unique=False)

    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('buyer_id != seller_id', name=op.f('ck_conversation_not_self')),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], name=op.f('fk_conversation_buyer_id_user')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_conversation_product_id_product')),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name=op.f('fk_conversation_seller_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation')),
    sa.UniqueConstraint('product_id', 'buyer_id', 'seller_id', name=op.f('uq_conversation_product_id'))
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_seller_id'), ['seller_id'], unique=False)

    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_image_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_image')),
    sa.UniqueConstraint('key', name=op.f('uq_product_image_key')),
    sa.UniqueConstraint('product_id', 'position', name=op.f('uq_product_image_product_id'))
    )
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_image_product_id'), ['product_id'], unique=False)

    op.create_table('product_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_view_product_id_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_product_view_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_view')),
    sa.UniqueConstraint('product_id', 'user_id', 'day', name=op.f('uq_product_view_product_id'))
    )
    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_view_product_id'), ['product_id'], unique=False)

    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1500), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_review_rating_range')),
    sa.CheckConstraint('reviewer_id != seller_id', name=op.f('ck_review_not_self')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_review_product_id_product')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], name=op.f('fk_review_reviewer_id_user')),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name=op.f('fk_review_seller_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review')),
    sa.UniqueConstraint('product_id', name=op.f('uq_review_product_id'))
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_seller_id'), ['seller_id'], unique=False)

    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_wishlist_product_id_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_wishlist_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wishlist')),
    sa.UniqueConstraint('user_id', 'product_id', name=op.f('uq_wishlist_user_id'))
    )
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_user_id'), ['user_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=3000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_message_conversation_id_conversation')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_message_sender_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_conversation_id'))

    op.drop_table('message')
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_product_id'))

    op.drop_table('wishlist')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_seller_id'))

    op.drop_table('review')
    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_view_product_id'))

    op.drop_table('product_view')
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_image_product_id'))

    op.drop_table('product_image')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_seller_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_buyer_id'))

    op.drop_table('conversation')
    with op.batch_alter_table('analytics_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_event_product_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_event_created_at'))

    op.drop_table('analytics_event')
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_session_user_id'))

    op.drop_table('user_session')
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_history_user_id'))

    op.drop_table('search_history')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_status'))
        batch_op.drop_index(batch_op.f('ix_report_reporter_id'))

    op.drop_table('report')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_seller_id'))
        batch_op.drop_index(batch_op.f('ix_product_price'))
        batch_op.drop_index('ix_product_discover')
        batch_op.drop_index(batch_op.f('ix_product_city'))
        batch_op.drop_index(batch_op.f('ix_product_category_id'))
        batch_op.drop_index(batch_op.f('ix_product_campus_id'))

    op.drop_table('product')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index('ix_notification_unread')

    op.drop_table('notification')
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_history_user_id'))

    op.drop_table('login_history')
    op.drop_table('admin_action')
    op.drop_table('account_token')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_campus_id'))

    op.drop_table('user')
    op.drop_table('category')
    op.drop_table('campus')
    # ### end Alembic commands ###
